name = "stock-blog"
compatibility_date = "2024-01-01"

# 최상위 레벨에 위치
pages_build_output_dir = ".next"

# D1 데이터베이스 바인딩
[[d1_databases]]
binding = "DB"
database_name = "stock-blog-db"
database_id = "0f90eae8-c6cd-4386-87ff-04bd9b6c90b4"